[package]
name = "tabs"
edition = "2018"
version = "0.1.0"
authors = ["application-services@mozilla.com"]
license = "MPL-2.0"

[features]
reqwest = ["sync15/reqwest"]
default = []

[dependencies]
sync15 = { path = "../sync15" }
serde = "1.0.101"
serde_derive = "1.0.101"
serde_json = "1.0.40"
log = "0.4.8"
lazy_static = "1.4.0"
url = "1.7.1"
failure = "0.1.6"
ffi-support = { path = "../support/ffi" }
interrupt = { path = "../support/interrupt" }
error-support = { path = "../support/error" }
sync-guid = { path = "../support/guid", features = ["random"] }

[dev-dependencies]
more-asserts = "0.2.1"
env_logger = "0.7.0"
prettytable-rs = "0.8.0"
fxa-client = { path = "../fxa-client" }
chrono = "0.4.8"
clap = "2.32.0"
cli-support = { path = "../support/cli" }
force-viaduct-reqwest = { path = "../support/force-viaduct-reqwest" }
